-- create "notes" table
CREATE TABLE "notes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "body" text NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "display_name" character varying NOT NULL, "profile_image" character varying NULL, "twitch_id" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'USER', "awards" jsonb NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"));
-- create index "users_twitch_id_key" to table: "users"
CREATE UNIQUE INDEX "users_twitch_id_key" ON "users" ("twitch_id");
-- create "posts" table
CREATE TABLE "posts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "pinned" boolean NOT NULL DEFAULT false, "title" character varying NOT NULL, "content" character varying NULL, "link" character varying NOT NULL, "moderation_comment" character varying NULL, "is_moderated" boolean NOT NULL DEFAULT false, "categories" post_categories NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "user_posts" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "posts_users_posts" FOREIGN KEY ("user_posts") REFERENCES "users" ("id") ON DELETE SET NULL);
-- create "comments" table
CREATE TABLE "comments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "content" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "post_comments" bigint NULL, "user_comments" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "comments_posts_comments" FOREIGN KEY ("post_comments") REFERENCES "posts" ("id") ON DELETE SET NULL, CONSTRAINT "comments_users_comments" FOREIGN KEY ("user_comments") REFERENCES "users" ("id") ON DELETE SET NULL);
-- create "user_liked_posts" table
CREATE TABLE "user_liked_posts" ("user_id" bigint NOT NULL, "post_id" bigint NOT NULL, PRIMARY KEY ("user_id", "post_id"), CONSTRAINT "user_liked_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE, CONSTRAINT "user_liked_posts_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE);
-- create "user_saved_posts" table
CREATE TABLE "user_saved_posts" ("user_id" bigint NOT NULL, "post_id" bigint NOT NULL, PRIMARY KEY ("user_id", "post_id"), CONSTRAINT "user_saved_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE, CONSTRAINT "user_saved_posts_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE);
