-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "display_name" character varying NOT NULL, "profile_image" character varying NULL, "twitch_id" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'USER', "awards" jsonb NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"));
-- create index "users_twitch_id_key" to table: "users"
CREATE UNIQUE INDEX "users_twitch_id_key" ON "users" ("twitch_id");
-- create "posts" table
CREATE TABLE "posts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "pinned" boolean NOT NULL DEFAULT false, "user_id" uuid NOT NULL, "title" character varying NOT NULL, "content" character varying NULL, "link" character varying NOT NULL, "moderation_comment" character varying NULL, "is_moderated" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "categories" character varying NOT NULL, PRIMARY KEY ("id"));
-- create "user_liked_posts" table
CREATE TABLE "user_liked_posts" ("user_id" bigint NOT NULL, "post_id" bigint NOT NULL, PRIMARY KEY ("user_id", "post_id"), CONSTRAINT "user_liked_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE, CONSTRAINT "user_liked_posts_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE);
-- create "user_saved_posts" table
CREATE TABLE "user_saved_posts" ("user_id" bigint NOT NULL, "post_id" bigint NOT NULL, PRIMARY KEY ("user_id", "post_id"), CONSTRAINT "user_saved_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE, CONSTRAINT "user_saved_posts_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE);
