// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/laclipasa/la-clipasa/ent/runtime.go

const (
	Version = "v0.14.1" // Version of ent codegen.
)
