// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/laclipasa/la-clipasa/ent/post"
)

// CreateCommentInput represents a mutation input for creating comments.
type CreateCommentInput struct {
	Content   string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *bool
	AuthorID  *int
	PostID    *int
}

// Mutate applies the CreateCommentInput on the CommentMutation builder.
func (i *CreateCommentInput) Mutate(m *CommentMutation) {
	m.SetContent(i.Content)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.DeletedAt; v != nil {
		m.SetDeletedAt(*v)
	}
	if v := i.AuthorID; v != nil {
		m.SetAuthorID(*v)
	}
	if v := i.PostID; v != nil {
		m.SetPostID(*v)
	}
}

// SetInput applies the change-set in the CreateCommentInput on the CommentCreate builder.
func (c *CommentCreate) SetInput(i CreateCommentInput) *CommentCreate {
	i.Mutate(c.Mutation())
	return c
}

// CreateNoteInput represents a mutation input for creating notes.
type CreateNoteInput struct {
	Title     string
	Body      string
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

// Mutate applies the CreateNoteInput on the NoteMutation builder.
func (i *CreateNoteInput) Mutate(m *NoteMutation) {
	m.SetTitle(i.Title)
	m.SetBody(i.Body)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
}

// SetInput applies the change-set in the CreateNoteInput on the NoteCreate builder.
func (c *NoteCreate) SetInput(i CreateNoteInput) *NoteCreate {
	i.Mutate(c.Mutation())
	return c
}

// CreatePostInput represents a mutation input for creating posts.
type CreatePostInput struct {
	Pinned            *bool
	Title             string
	Content           *string
	Link              string
	ModerationComment *string
	IsModerated       *bool
	CreatedAt         *time.Time
	UpdatedAt         *time.Time
	Categories        post.Categories
	AuthorID          *int
	CommentIDs        []int
	SavedByIDs        []int
	LikedByIDs        []int
}

// Mutate applies the CreatePostInput on the PostMutation builder.
func (i *CreatePostInput) Mutate(m *PostMutation) {
	if v := i.Pinned; v != nil {
		m.SetPinned(*v)
	}
	m.SetTitle(i.Title)
	if v := i.Content; v != nil {
		m.SetContent(*v)
	}
	m.SetLink(i.Link)
	if v := i.ModerationComment; v != nil {
		m.SetModerationComment(*v)
	}
	if v := i.IsModerated; v != nil {
		m.SetIsModerated(*v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	m.SetCategories(i.Categories)
	if v := i.AuthorID; v != nil {
		m.SetAuthorID(*v)
	}
	if v := i.CommentIDs; len(v) > 0 {
		m.AddCommentIDs(v...)
	}
	if v := i.SavedByIDs; len(v) > 0 {
		m.AddSavedByIDs(v...)
	}
	if v := i.LikedByIDs; len(v) > 0 {
		m.AddLikedByIDs(v...)
	}
}

// SetInput applies the change-set in the CreatePostInput on the PostCreate builder.
func (c *PostCreate) SetInput(i CreatePostInput) *PostCreate {
	i.Mutate(c.Mutation())
	return c
}

// CreateUserInput represents a mutation input for creating users.
type CreateUserInput struct {
	DisplayName  string
	ProfileImage *string
	TwitchID     string
	Awards       []string
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	DeletedAt    *time.Time
	SavedPostIDs []int
	LikedPostIDs []int
	PostIDs      []int
	CommentIDs   []int
}

// Mutate applies the CreateUserInput on the UserMutation builder.
func (i *CreateUserInput) Mutate(m *UserMutation) {
	m.SetDisplayName(i.DisplayName)
	if v := i.ProfileImage; v != nil {
		m.SetProfileImage(*v)
	}
	m.SetTwitchID(i.TwitchID)
	if v := i.Awards; v != nil {
		m.SetAwards(v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.DeletedAt; v != nil {
		m.SetDeletedAt(*v)
	}
	if v := i.SavedPostIDs; len(v) > 0 {
		m.AddSavedPostIDs(v...)
	}
	if v := i.LikedPostIDs; len(v) > 0 {
		m.AddLikedPostIDs(v...)
	}
	if v := i.PostIDs; len(v) > 0 {
		m.AddPostIDs(v...)
	}
	if v := i.CommentIDs; len(v) > 0 {
		m.AddCommentIDs(v...)
	}
}

// SetInput applies the change-set in the CreateUserInput on the UserCreate builder.
func (c *UserCreate) SetInput(i CreateUserInput) *UserCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateUserInput represents a mutation input for updating users.
type UpdateUserInput struct {
	DisplayName        *string
	ClearProfileImage  bool
	ProfileImage       *string
	TwitchID           *string
	ClearAwards        bool
	Awards             []string
	AppendAwards       []string
	UpdatedAt          *time.Time
	ClearDeletedAt     bool
	DeletedAt          *time.Time
	ClearSavedPosts    bool
	AddSavedPostIDs    []int
	RemoveSavedPostIDs []int
	ClearLikedPosts    bool
	AddLikedPostIDs    []int
	RemoveLikedPostIDs []int
	ClearPosts         bool
	AddPostIDs         []int
	RemovePostIDs      []int
	ClearComments      bool
	AddCommentIDs      []int
	RemoveCommentIDs   []int
}

// Mutate applies the UpdateUserInput on the UserMutation builder.
func (i *UpdateUserInput) Mutate(m *UserMutation) {
	if v := i.DisplayName; v != nil {
		m.SetDisplayName(*v)
	}
	if i.ClearProfileImage {
		m.ClearProfileImage()
	}
	if v := i.ProfileImage; v != nil {
		m.SetProfileImage(*v)
	}
	if v := i.TwitchID; v != nil {
		m.SetTwitchID(*v)
	}
	if i.ClearAwards {
		m.ClearAwards()
	}
	if v := i.Awards; v != nil {
		m.SetAwards(v)
	}
	if i.AppendAwards != nil {
		m.AppendAwards(i.Awards)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if i.ClearDeletedAt {
		m.ClearDeletedAt()
	}
	if v := i.DeletedAt; v != nil {
		m.SetDeletedAt(*v)
	}
	if i.ClearSavedPosts {
		m.ClearSavedPosts()
	}
	if v := i.AddSavedPostIDs; len(v) > 0 {
		m.AddSavedPostIDs(v...)
	}
	if v := i.RemoveSavedPostIDs; len(v) > 0 {
		m.RemoveSavedPostIDs(v...)
	}
	if i.ClearLikedPosts {
		m.ClearLikedPosts()
	}
	if v := i.AddLikedPostIDs; len(v) > 0 {
		m.AddLikedPostIDs(v...)
	}
	if v := i.RemoveLikedPostIDs; len(v) > 0 {
		m.RemoveLikedPostIDs(v...)
	}
	if i.ClearPosts {
		m.ClearPosts()
	}
	if v := i.AddPostIDs; len(v) > 0 {
		m.AddPostIDs(v...)
	}
	if v := i.RemovePostIDs; len(v) > 0 {
		m.RemovePostIDs(v...)
	}
	if i.ClearComments {
		m.ClearComments()
	}
	if v := i.AddCommentIDs; len(v) > 0 {
		m.AddCommentIDs(v...)
	}
	if v := i.RemoveCommentIDs; len(v) > 0 {
		m.RemoveCommentIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateUserInput on the UserUpdate builder.
func (c *UserUpdate) SetInput(i UpdateUserInput) *UserUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateUserInput on the UserUpdateOne builder.
func (c *UserUpdateOne) SetInput(i UpdateUserInput) *UserUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
