// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NoteInput struct {
	Title      string `json:"title"`
	Body       string `json:"body"`
	ExtraField string `json:"extraField"`
}
