// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/laclipasa/la-clipasa/ent"
	"github.com/laclipasa/la-clipasa/ent/user"
)

type AdminUpdateUserInput struct {
	BaseInput *ent.UpdateUserInput `json:"baseInput"`
	Role      user.Role            `json:"role"`
}

type NoteInput struct {
	Title      string `json:"title"`
	Body       string `json:"body"`
	ExtraField string `json:"extraField"`
}
